FROM mysql

ENV MYSQL_USER=gaebaljoah
ENV MYSQL_PASSWORD=joah1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=joahdb

CMD [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]